#!/usr/bin/env bash

clear
echo "Welcome to Guibi's dotfiles!"

echo "Looking for Nix..."
if ! command -v nix > /dev/null 2>&1; then
    echo "Nix is not installed. Running the install script and exiting."
    curl -fsSL https://install.determinate.systems/nix | sh -s -- install --determinate
    echo "Please open a new terminal and run this script again."
    echo "If nix couldn't install or w/e, here's the script to run:"
    echo "curl -fsSL https://install.determinate.systems/nix | sh -s -- install --determinate"
    exit 1
fi

echo "Nix is installed. Continuing with the rest of the script..."
echo ""

echo "Cloning repo..."
nix-shell -p git --run "git clone https://github.com/Guibi1/.dotfiles ~/nix-config"

cp ~/nix-config/vars.exemple.nix ~/nix-config/vars.nix
nix-shell -p nano --run "nano ~/nix-config/vars.nix"
clear
echo "Vars editing complete!"
echo ""

if grep -q 'NAME=NixOS' /etc/os-release; then
    echo "You are running NixOS!"

    echo "Switching NixOS to unstable channel..."
    sudo nix-channel --quiet --add https://nixos.org/channels/nixos-unstable nixos

    echo "Adding Home Manager unstable channel..."
    sudo nix-channel --quiet --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager

    echo "Updating channels..."
    sudo nix-channel --update

    echo "Linking config..."
    sudo ln -sf ~/nix-config/nixos-config.nix /etc/nixos/configuration.nix

    echo "Switching..."
    sudo nixos-rebuild switch --upgrade
elif [[ "$(uname)" == "Darwin" ]]; then
    echo "You are on MacOS!"
    echo "I hope you disabled Hyprland!"
    echo ""
    sleep 5

    echo "Adding NixPkgs unstable channel..."
    nix-channel --quiet --add https://nixos.org/channels/nixpkgs-unstable nixpkgs

    echo "Adding NixDarwin unstable channel..."
    nix-channel --quiet --add https://github.com/LnL7/nix-darwin/archive/master.tar.gz darwin

    echo "Adding Home Manager unstable channel..."
    nix-channel --quiet --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager

    echo "Updating channels..."
    nix-channel --update

    echo "Building NixDarwin..."
    nix-build '<darwin>' -A darwin-rebuild
        
    echo "Switching..."
    ./result/bin/darwin-rebuild switch -I darwin-config=$HOME/nix-config/darwin-config.nix
    sudo rm -r result
else
    echo "You are running Linux!"

    if command -v home-manager &> /dev/null ; then
        echo "Home Manager is already installed!"
    else
        echo "Adding Home Manager unstable channel..."
        nix-channel --quiet --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager

        echo "Updating channels..."
        nix-channel --quiet --update
        
        echo "Installing Home Manager..."
        nix-shell '<home-manager>' -A install
    fi

    echo "Linking Home Manager config..."
    rm -rf ~/.config/home-manager
    ln -sf ~/nix-config ~/.config/home-manager

    echo "Switching..."
    export NIXPKGS_ALLOW_UNFREE=1
    home-manager switch
fi

echo "All done!"
echo "You should probably reboot"
