#!/usr/bin/env bash

clear
echo "Welcome to Guibi1's dotfiles"

echo "Looking for Nix..."
if ! command -v nix > /dev/null 2>&1; then
    echo "Nix is not installed. Running the install script and exiting."
    sh <(curl -fsSL https://nixos.org/nix/install) --daemon
    echo "Please open a new terminal and run this script again."
    echo "If nix couldn't install or w/e, here's the script to run:"
    echo "sh <(curl -fsSL https://nixos.org/nix/install) --daemon"
    exit 1
fi

echo "Nix is installed. Continuing with the rest of the script..."
echo ""

echo "Cloning repo..."
nix-shell -p git --run "git clone https://github.com/Guibi1/.dotfiles ~/nix-config"

cp ~/nix-config/vars.exemple.nix ~/nix-config/vars.nix
nano ~/nix-config/vars.nix
clear
echo "Vars editing complete!"
echo ""

if grep -q 'NAME=NixOS' /etc/os-release; then
    echo "You are running NixOS!"

    echo "Switching NixOS to unstable channel..."
    sudo nix-channel --quiet --add https://nixos.org/channels/nixos-unstable nixos
    sudo nix-channel --quiet --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
    sudo nix-channel --update

    echo "Linking config and switching..."
    sudo ln -sf ~/nix-config/nixos-config.nix /etc/nixos/configuration.nix
    sudo nixos-rebuild switch --upgrade
elif ;then
    echo "You are on MacOS!"
    echo "I hope you disabled Hyprland!"
    echo ""
    sleep 5

    echo "Switching NixOS to unstable channel..."
    nix-channel --quiet --add https://nixos.org/channels/nixos-unstable nixos
    nix-channel --quiet --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
    nix-channel --update

    echo "Building config and switching..."
    darwin-rebuild switch -I darwin-config=$HOME/nix-config/darwin-config.nix
else
    echo "You are not on NixOS, skipping nixos-config..."
    echo "I hope you disabled Hyprland!"
    echo ""
    sleep 5

    if command -v home-manager &> /dev/null ; then
        echo "Home Manager is already installed!"
    else
        echo "Installing Home Manager..."
        nix-channel --quiet --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
        nix-channel --quiet --update
        nix-shell '<home-manager>' -A install
    fi

    echo ""
    echo "Linking Home Manager config and switching..."
    rm -rf ~/.config/home-manager
    ln -sf ~/nix-config ~/.config/home-manager

    export NIXPKGS_ALLOW_UNFREE=1
    home-manager switch
fi


fish -c "tide configure --auto --style=Lean --prompt_colors='True color' --show_time=No --lean_prompt_height='Two lines' --prompt_connection=Dotted --prompt_connection_andor_frame_color=Dark --prompt_spacing=Sparse --icons='Few icons' --transient=Yes"

echo "All done!"
echo "You should probably reboot"
