# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-20b6902a-970c-412d-9e18-86956af76da2";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-20b6902a-970c-412d-9e18-86956af76da2".device = "/dev/disk/by-uuid/20b6902a-970c-412d-9e18-86956af76da2";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2E51-386B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/d" =
    { device = "/dev/disk/by-uuid/962CC79E2CC7782F";
      fsType = "ntfs-3g"; 
      options = [ "rw" "uid=guibi" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
